### ISSUE TITLE
run mellplay but got exception

### ISSUE THREAD

**Issue by ncisoft** [Mellcap/MellPlayer#5]
Environment:
debian jessie i386
mpv/stable,stable,stable,now 0.6.2-2 i386 [installed]
libmpv-dev/stable,stable,stable,now 0.6.2-2 i386 [installed]

Traceback (most recent call last):
  File "/usr/local/bin/mellplayer", line 9, in <module>
    load_entry_point('MellPlayer==0.1.1.1', 'console_scripts', 'mellplayer')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/mellplayer/start.py", line 11, in <module>
    from mellplayer.controller import mell_ui, initial_player
  File "/usr/local/lib/python3.4/dist-packages/mellplayer/controller.py", line 12, in <module>
    from mellplayer.player import mell_player
  File "/usr/local/lib/python3.4/dist-packages/mellplayer/player.py", line 16, in <module>
    from mellplayer.utils.mpv import MPV
  File "/usr/local/lib/python3.4/dist-packages/mellplayer/utils/mpv.py", line 307, in <module>
    _handle_func('mpv_create_client',           [c_char_p],                                 MpvHandle, notnull_errcheck)
  File "/usr/local/lib/python3.4/dist-packages/mellplayer/utils/mpv.py", line 268, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/i386-linux-gnu/libmpv.so.1: undefined symbol: mpv_create_client

**Comment by Mellcap** [comment]
Thank you, there are some bugs in linux, I will fix it as soon as possible 😄

**Comment by Mellcap** [comment]
@ncisoft Debian may not only depends on `mpv` and `libmpv-dev`, when I find out I will tell you. Or if you find it out, you can create a pull request.
